name: flutter_facebook_auth_web
description: web support for flutter_facebook_auth
version: 6.0.0-dev.2
homepage: https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth_web


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
#  flutter_facebook_auth_platform_interface: ^6.0.0-dev.2
  
  flutter_facebook_auth_platform_interface:
    git:
      url: git@github.com:brancedev/flutter-facebook-auth.git
      path: facebook_auth_platform_interface
      ref: 4e4faa520e1f469cb239d1ca16e28b5d56a7aafa
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterFacebookAuthPlugin
        fileName: flutter_facebook_auth_web.dart
