name: facebook_auth_desktop
description: macOS support for flutter_facebook_auth
version: 2.0.0-dev.2
homepage: https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth_desktop

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  flutter_secure_storage: ^9.0.0
  #  flutter_facebook_auth_platform_interface: ^6.0.0-dev.2

  flutter_facebook_auth_platform_interface:
    git:
      url: git@github.com:brancedev/flutter-facebook-auth.git
      path: facebook_auth_platform_interface
      ref: 2e1d0916eaca44295291cdf8d333621d768db9da


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: flutter_facebook_auth
    platforms:
      macos:
        pluginClass: FacebookAuthDesktopPlugin
        dartPluginClass: FacebookAuthDesktopPlugin